### ISSUE TITLE
Update instance types for smart pokemon

### ISSUE THREAD

**Issue by Fabio1988** [PickleRickVE/RealDeviceMap-tools#15]
RDM provides a new instance type, please provide this value 'circle_smart_pokemon' on LINE 1566 in index.php

**Comment by Pogodenhelder** [comment]
you might want to reopen this since this is still not pushed and a issue.

**Comment by PickleRickVE** [comment]
Had to fix the import for circle instances first. The addition of the smart instance is ready but I had to update my own installation to test it.

**Comment by Fabio1988** [comment]
I tried latest, but it's not possible to import instances at all, they are not listed in Importing Instance... What did change?

**Comment by PickleRickVE** [comment]
This seems to be a different problem. Can you contact me on discord via dm? Should be the better place to continue.
