### ISSUE TITLE
New Nest-Tag

### ISSUE THREAD

**Issue by Un1matr1x** [PickleRickVE/RealDeviceMap-tools#4]
use the following query to get all nests

http://overpass-turbo.eu/s/iDh

**Comment by PickleRickVE** [comment]
It's way more precise. Will be exchanged.

**Comment by PickleRickVE** [comment]
I had to adapt it for performance, it's still better than before.

**Comment by Un1matr1x** [comment]
isn't it done by 1915c704763370d7507ce268e343e8d13387e530 ?

**Comment by PickleRickVE** [comment]
Wanted to test before closing. But you're right, it's done.
