### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by EntroFlux** [PickleRickVE/RealDeviceMap-tools#7]
I  am obilivious as to how to set up this on docker....I suppose my first question is does it increase performance...second would be some guidance on the install...also I get this when visting certain places in this instance Tokyo 
![tools](https://user-images.githubusercontent.com/43960406/74493343-7e0c8780-4e97-11ea-9ab2-779610e3401e.JPG)

..please... Flux

**Comment by PickleRickVE** [comment]
Docker wasn’t integrated for performance. Didn’t even think about it till now. It’s only for those who have difficulties to connect to their database. A guide can be found here: https://github.com/PickleRickVE/RealDeviceMap-tools/wiki/installation
