### ISSUE TITLE
import instance data

### ISSUE THREAD

**Issue by Fabio1988** [PickleRickVE/RealDeviceMap-tools#8]
Hy

At importing pokemon circle instances data it will always choose 70m circles (if I don't enter own radius manually).

The higher Pokemon range of 500m depends on latitude, maybe it would be possible to create those circles with the right size automatically? So choose if you want to import circles for 70m IV scanning or higher range with approx. 500m for pokemon without IV?

And after importing instance data it won't show the radius size of the circle. If I create a circle manually, it will display the radius size.

**Comment by PickleRickVE** [comment]
It depends on the instance type which you import. A circle pokemon instance is correctly imported with 70m as it is meant for iv. The one you want is the circle raid instance, where the range is automatically calculated. It imports the type you've set in rdm. You can even set the half range in settings for 1G devices like 5s. 

Didn't built in the radius for imported circles yet. Shouldn't be a big thing.

**Comment by Fabio1988** [comment]
Yeah I know that. But I use Pokemon Circle for Pokemon Circle for bigger radius incl. Raid Scan.  Additionally I have a IV Instance with Fence, for Prio Queue. Should I switch the pokemon circle instance to circle raid instance? Is it the same output as pokemon circle with bigger radius?
