### ISSUE TITLE
Read only db access

### ISSUE THREAD

**Issue by lenisko** [PickleRickVE/RealDeviceMap-tools#9]
Hey there!

From what I can see, whole script is **only reading** data from database, unless I'm wrong?

Based on that I believe it's safe to give out access to this tool to normal users? for example to let them fix adjust paths or make corrections. If so maybe it's worth mentioning this fact along with possibility of using read-only database user just to make things safer?

Cheers!

**Comment by PickleRickVE** [comment]
Since I made some changes, it's no longer completely read only. But the write functions are only for manualdb, rdm db is still read-only.

**Comment by lenisko** [comment]
@PickleRickVE Thanks for letting me know. I will go through commits someday. For now I'm using private fork with some changes based on previous version.
